import React, { Component } from 'react';

export default class DefaultPage extends Component {
  render() {
    return (
      <div><p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in semper odio. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec nibh egestas, lobortis neque et, laoreet ipsum. Phasellus eu eros facilisis, rutrum ante at, lobortis magna. Ut eleifend, urna eget pellentesque hendrerit, est odio feugiat diam, eget tempus purus lorem vel nulla. Pellentesque eget libero lacus. Nunc id velit facilisis, vehicula purus ultricies, pretium erat. Nunc ut ex id lacus dapibus laoreet. Maecenas aliquet felis vel nisl volutpat, a venenatis lorem facilisis. Ut luctus nisi a ultricies sodales. Nullam mollis turpis tellus, ac ultricies est finibus sed. Donec varius fringilla massa, at dictum libero finibus ac. Aliquam ullamcorper tortor risus, vitae fringilla purus tempus at. Integer efficitur bibendum tellus, mattis ornare neque porta eget. 
Sed eget mi eget magna condimentum porttitor vel nec massa. Suspendisse venenatis pretium volutpat. Quisque vitae orci mattis, sagittis diam ullamcorper, porttitor sem. Maecenas magna metus, vulputate nec dolor a, pretium fermentum est. Mauris sed eros nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas blandit viverra arcu vel congue. 
Mauris eget magna at lectus tempor efficitur vel at dui. Maecenas mattis neque eu efficitur aliquet. Nulla mattis hendrerit malesuada. Quisque rutrum porta lorem vitae pulvinar. Fusce at rutrum turpis, ac ullamcorper massa. Duis interdum nisi eget tincidunt blandit. In quis faucibus ligula. Curabitur nec quam eu nibh pharetra hendrerit. Donec quam felis, laoreet vel interdum a, aliquet ac tellus. Vivamus finibus blandit elit nec condimentum. Pellentesque vel gravida justo. Vivamus convallis lacus bibendum orci tincidunt ornare. Phasellus ullamcorper justo arcu, at vehicula ex consequat eu. Vestibulum lobortis eget leo eget vulputate. 
Morbi justo ex, euismod quis odio ac, tristique imperdiet neque. Nunc quis est a dolor sodales hendrerit id nec diam. Quisque in felis lacinia, molestie urna ac, faucibus dui. Praesent dapibus metus a leo porta volutpat. Cras ut dolor ut ipsum malesuada ultricies. Vivamus ullamcorper neque luctus efficitur bibendum. Maecenas nulla purus, sagittis sodales iaculis nec, bibendum eu purus. Proin accumsan augue ut libero finibus sollicitudin sed et ligula. Nulla facilisi. Donec finibus sapien eget bibendum vulputate. 
Nulla vitae vehicula urna. Morbi ultrices volutpat tortor, lobortis suscipit ex luctus ac. Nulla posuere felis arcu, nec cursus metus molestie vel. Cras tincidunt turpis urna, ut suscipit mauris ultrices sed. In id pellentesque est, vitae cursus libero. Praesent faucibus sem a magna convallis, non tempor elit cursus. Suspendisse nec arcu sollicitudin, consequat orci ut, convallis magna. Praesent felis sem, condimentum ac velit eu, bibendum elementum odio. Maecenas placerat purus et velit ultricies vulputate. 
</p></div>
    );
  }
}
