export const AUTH_ACTIONS = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT'
}

export const DASHBOARD_ACTIONS = {
    FETCHING: 'FETCHING_SUBJECTS',
    FETCHED_ACTIVE: 'FETCH_ACTIVE_COMPLETED',
    FETCHED_OPEN: 'FETCH_OPEN_COMPLETED',
    FETCHED_OLD: 'FETCH_OLD_COMPLETED',
    REMOVE: 'REMOVE_SUBJECT'
}

export const LOAD_ACTIONS = {
    START: 'START_LOADING',
    STOP: 'STOP_LOADING'
}

export const REGISTER_SUB_ACTIONS = {
    ADDING: 'ADDING_SUBJECT',
    ADDED: 'ADDED_SUBJECT'
}

export const SUBJECT_PAGE_ACTIONS = {
    FETCHED: 'SUBJECT_PAGE_FETCHED',
    STUDENT_REGISTRED: 'STUDENT_REGISTRED'
}